import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Modal, ModalProps } from "../components/Modal";
import { TimetableDataTable } from "../components/TimetableDataTable";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.example.simplerTimes.useQuery(undefined, {
    refetchOnWindowFocus: false,
  });
    // eslint-disable-next-line prefer-const
    let [showModal, setShowModal] = React.useState(false);
    const [modalData, setModalData] = React.useState<
      Omit<ModalProps, "setShowModal">
    >({
      body: "",
      title: "",
    });
  if (isLoading || data === undefined) {
    return null;
  }
  return (
    <>
      <Head>
        <title>Edinburgh Leisure Data View</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center p-4">
        <h1 className="my-4 text-4xl font-bold">Edinburgh Leisure Data View</h1>
        <TimetableDataTable data={data} setShowModal={setShowModal} setModalData={setModalData} />
      </main>
      {showModal && <Modal {...modalData} setShowModal={setShowModal} />}
    </>
  );
};

export default Home;
